# Image Processing in NumPy

In [2]:
import numpy as np

 ---------------------------------------------------
### 1. Create grayscale image matrix
A grayscale image contains only shades of gray.

Each pixel stores a single intensity:

| Value         | Color          |
| ------------- | -------------- |
| 0             | Black          |
| 255           | White          |
| Between 0–255 | Shades of Gray |


In [3]:
grayscale_image = np.array([
    [50, 100, 150],
    [200, 250, 100],
    [25, 75, 125]
], dtype=np.uint8)

print("Grayscale Image Matrix:\n")
print(grayscale_image)

Grayscale Image Matrix:

[[ 50 100 150]
 [200 250 100]
 [ 25  75 125]]


 ---------------------------------------------------
### 2. Invert image colors
- Formula:
- inverted = 255 - pixel_value

In [6]:
inverted_image = 255 - grayscale_image

print("Inverted Image:\n")
print(inverted_image)

Inverted Image:

[[205 155 105]
 [ 55   5 155]
 [230 180 130]]


 ---------------------------------------------------
### 3. Brightness increase/decrease

In [7]:
# Increase brightness
bright_image = np.clip(grayscale_image + 50, 0, 255)

# Decrease brightness
dark_image = np.clip(grayscale_image - 50, 0, 255)

print("\nBrightness Increased:\n")
print(bright_image)

print("\nBrightness Decreased:\n")
print(dark_image)


Brightness Increased:

[[100 150 200]
 [250  44 150]
 [ 75 125 175]]

Brightness Decreased:

[[  0  50 100]
 [150 200  50]
 [231  25  75]]


 ---------------------------------------------------
### 4. Crop image using slicing

In [11]:
image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

cropped = image[1:3, 1:3]

print("Original Image:")
print(image)

print("\nCropped Image:")
print(cropped)

Original Image:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Cropped Image:
[[ 60  70]
 [100 110]]


 ---------------------------------------------------
### 5. Blur image manually
- Simple averaging blur

In [17]:
image = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
], dtype=float)

print('Original image:\n', image)

blurred = np.zeros_like(image)

for i in range(1, image.shape[0]-1):
    for j in range(1, image.shape[1]-1):
        blurred[i, j] = np.mean(image[i-1:i+2, j-1:j+2])

print("\nBlurred Image:")
print(blurred)

Original image:
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]

Blurred Image:
[[ 0.  0.  0.]
 [ 0. 50.  0.]
 [ 0.  0.  0.]]


 ---------------------------------------------------
### 6. Detect edges basics
- Simple edge detection using difference

In [19]:
image = np.array([
    [10, 10, 10],
    [10, 255, 10],
    [10, 10, 10]
])

edges = np.abs(np.diff(image, axis=1))

print("Edge Detection Result:\n")
print(edges)

Edge Detection Result:

[[  0   0]
 [245 245]
 [  0   0]]


 ---------------------------------------------------
### 7. Flip image horizontally

In [20]:
image = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

horizontal_flip = image[:, ::-1]

print("Horizontally Flipped Image:\n")
print(horizontal_flip)

Horizontally Flipped Image:

[[3 2 1]
 [6 5 4]]


 ---------------------------------------------------
### 8. Flip image vertically

In [21]:
vertical_flip = image[::-1]

print("\nVertically Flipped Image:\n")
print(vertical_flip)


Vertically Flipped Image:

[[4 5 6]
 [1 2 3]]


 ---------------------------------------------------
### 9. RGB → grayscale conversion
- Formula:
- Gray = 0.299R + 0.587G + 0.114B

In [23]:
rgb_image = np.array([
    [[255, 0, 0], [0, 255, 0]],
    [[0, 0, 255], [255, 255, 255]]
])

grayscale = np.dot(
    rgb_image[..., :3],
    [0.299, 0.587, 0.114]
)

print("RGB Image:")
print(rgb_image)

print("\nConverted Grayscale Image:")
print(grayscale.astype(int))

RGB Image:
[[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255 255]]]

Converted Grayscale Image:
[[ 76 149]
 [ 29 255]]


 ---------------------------------------------------
### 10. Create pixel art generator

In [25]:
# 0 = Black
# 1 = White

pixel_art = np.array([
    [0, 1, 0, 1, 0],
    [1, 0, 1, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 0, 1, 0, 1],
    [0, 1, 0, 1, 0]
])

print("Pixel Art:\n")

for row in pixel_art:
    for pixel in row:
        if pixel == 1:
            print("⬜", end=" ")
        else:
            print("⬛", end=" ")
    print()

Pixel Art:

⬛ ⬜ ⬛ ⬜ ⬛ 
⬜ ⬛ ⬜ ⬛ ⬜ 
⬛ ⬜ ⬜ ⬜ ⬛ 
⬜ ⬛ ⬜ ⬛ ⬜ 
⬛ ⬜ ⬛ ⬜ ⬛ 


 ---------------------------------------------------
###