---
# Weather Data Analyzer
---

In [1]:
import numpy as np

# Number of days
days = int(input("Enter number of days: "))

temperature = []

# Input temperatures
for i in range(days):

    temp = float(input(f"Enter temperature for Day {i+1}: "))

    temperature.append(temp)

# Convert to NumPy array
temperature = np.array(temperature)

print("\nTemperature Dataset:")
print(temperature)


Temperature Dataset:
[36. 45. 23. 21. 38.]


### Basic Weather Analysis

In [2]:
print("----- WEATHER ANALYSIS -----\n")

print("Average Temperature:",
      np.mean(temperature))

print("Maximum Temperature:",
      np.max(temperature))

print("Minimum Temperature:",
      np.min(temperature))

print("Total Temperature Sum:",
      np.sum(temperature))

----- WEATHER ANALYSIS -----

Average Temperature: 32.6
Maximum Temperature: 45.0
Minimum Temperature: 21.0
Total Temperature Sum: 163.0


### Find Hot & Cold Days

In [3]:
# Hot days (>35)
hot_days = temperature[temperature > 35]

# Cold days (<20)
cold_days = temperature[temperature < 20]

print("Hot Days Temperatures:")
print(hot_days)

print("\nCold Days Temperatures:")
print(cold_days)

Hot Days Temperatures:
[36. 45. 38.]

Cold Days Temperatures:
[]


### Detect Rainy Days

In [4]:
rainy_days = temperature[temperature < 25]

print("Possible Rainy Days:")
print(rainy_days)

Possible Rainy Days:
[23. 21.]


### Celsius → Fahrenheit Conversion
- Formula

- F=(C × 5/9)+32

In [5]:
fahrenheit = (temperature * 9/5) + 32

print("Temperature in Fahrenheit:")
print(fahrenheit)

Temperature in Fahrenheit:
[ 96.8 113.   73.4  69.8 100.4]


### Weather Conditions Detector

In [ ]:
print("----- WEATHER CONDITIONS -----\n")

for temp in temperature:

    if temp >= 40:
        print(temp, "°C -> Very Hot")

    elif temp >= 30:
        print(temp, "°C -> Sunny")

    elif temp >= 20:
        print(temp, "°C -> Pleasant")

    else:
        print(temp, "°C -> Cold")

----- WEATHER CONDITIONS -----

36.0 °C -> Sunny
45.0 °C -> Very Hot
23.0 °C -> Pleasant
21.0 °C -> Pleasant
38.0 °C -> Sunny


### Find Hottest Day

In [7]:
hottest_day = np.argmax(temperature)

print("Hottest Day Index:",
      hottest_day)

print("Hottest Temperature:",
      temperature[hottest_day])

Hottest Day Index: 1
Hottest Temperature: 45.0


### Temperature Normalization

In [8]:
normalized_temp = (
    (temperature - np.min(temperature))
    /
    (np.max(temperature) - np.min(temperature))
)

print("\nNormalized Temperature:")
print(normalized_temp)


Normalized Temperature:
[0.625      1.         0.08333333 0.         0.70833333]


### Weekly Weather Report

In [9]:
print("\n----- WEEKLY WEATHER REPORT -----")

for i in range(days):
    print(f"Day {i+1} -> {temperature[i]} °C")


----- WEEKLY WEATHER REPORT -----
Day 1 -> 36.0 °C
Day 2 -> 45.0 °C
Day 3 -> 23.0 °C
Day 4 -> 21.0 °C
Day 5 -> 38.0 °C


---