# Linear Algebra

In [1]:
import numpy as np

 ---------------------------------------------------
### 1. Matrix multiplication

In [6]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

matrix_multi = np.matmul(A, B)

print("\nMatrix Multiplication:\n", matrix_multi)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix Multiplication:
 [[19 22]
 [43 50]]


 ---------------------------------------------------
### 2. Dot product

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nDot Product:", dot_product)

Array 1: [1 2 3]
Array 2: [4 5 6]

Dot Product: 32


 ---------------------------------------------------
### 3. Cross product

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

cross_product = np.cross(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nCross Product:", cross_product)

Array 1: [1 2 3]
Array 2: [4 5 6]

Cross Product: [-3  6 -3]


 ---------------------------------------------------
### 4. Transpose matrix

In [11]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transpose = matrix.T

print("Matrix:\n", matrix)

print("\nTranspose Matrix:\n", transpose)

Matrix:
 [[1 2 3]
 [4 5 6]]

Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]


 ---------------------------------------------------
### 5. Find determinant
- Central Formula:
- det(A) = ad - bc

In [14]:
matrix = np.array([
    [4, 6],
    [3, 8]
])

print("Matrix:\n", matrix)

determinant = np.linalg.det(matrix)

print("\nDeterminant:", determinant)

# Formula Visualization
# det(A) = ad - bc
# :contentReference[oaicite:0]{index=0}

Matrix:
 [[4 6]
 [3 8]]

Determinant: 14.000000000000004


 ---------------------------------------------------
### 6. Find inverse matrix

 ---------------------------------------------------
### 7. Solve linear equations
- System representation:
- Ax = b

 ---------------------------------------------------
### 8. Find eigenvalues & eigenvectors

 ---------------------------------------------------
### 9. Calculate matrix rank

 ---------------------------------------------------
### 10. Build simple recommendation score matrix

 ---------------------------------------------------
###